# Generated by Django 5.0.6 on 2024-07-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['sname', 'studentid'], 'verbose_name': 'student'},
        ),
        migrations.CreateModel(
            name='reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_marksheet_generation', models.DateField(auto_created=True)),
                ('student_rank', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='vege.student')),
            ],
        ),
    ]
