# Generated by Django 5.0.6 on 2024-07-10 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_alter_reportcard_date_of_marksheet_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 7, 10, 7, 14, 10, 443911, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
